# yaml-language-server: $schema=https://raw.githubusercontent.com/camptocamp/c2cciutils/1.2.14/c2cciutils/schema.json

checks:
  versions:
    rebuild: False
  codespell:
    arguments:
      - --quiet-level=2
      - --check-filenames
      - --ignore-words-list=nd
  required_workflows: False

publish:
  docker: false
