checks:
  print_versions:
    versions:
      - cmd:
          - c2cciutils
          - --version
        name: c2cciutils
      - cmd:
          - python3
          - --version
        name: python
      - cmd:
          - python3
          - -m
          - pip
          - --version
        name: pip
      - cmd:
          - docker
          - --version
        name: docker

audit:
  snyk:
    pip_install_arguments:
      - --user
      - --ignore-installed
